@echo off
echo Generating Prisma client...
npx prisma generate

echo Pushing schema to database...
npx prisma db push

echo Seeding the database...
npm run seed

echo Starting the development server...
npm run dev 